baseurl: "http://vanilla.github.io/docs"
title: "Vanilla Forums Documentation"

contentdir: "content"
layoutdir: "layouts"
publishdir: "public"

canonifyurls: true

params:
    description: "Vanilla Forums Documentation"
    author: "Vanilla Community"

    links:
        docs: "http://docs.vanillaforums.com"
        blog: "https://blog.vanillaforums.com"
        cloud: "https://vanillaforums.com"
        community: "https://vanillaforums.org/discussions"
        github: "https://github.com/vanilla/vanilla"
        issues: "https://github.com/vanilla/vanilla/issues"
    
taxonomies:
    category: "categories"
    tag: "tags"
    series: "series"
